"""create device inventory table

Revision ID: 252f23614acf
Revises: c1d2e3f4b5a6
Create Date: 2026-08-19 15:08:42.552157
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252f23614acf'
down_revision = 'c1d2e3f4b5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_inventories', sa.Column('cpu_info', sa.JSON(), nullable=True))
    op.add_column('device_inventories', sa.Column('ram_info', sa.JSON(), nullable=True))
    op.add_column('device_inventories', sa.Column('disk_info', sa.JSON(), nullable=True))
    op.add_column('device_inventories', sa.Column('network_interfaces', sa.JSON(), nullable=True))
    op.add_column('device_inventories', sa.Column('operating_system_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_inventories', 'operating_system_info')
    op.drop_column('device_inventories', 'network_interfaces')
    op.drop_column('device_inventories', 'disk_info')
    op.drop_column('device_inventories', 'ram_info')
    op.drop_column('device_inventories', 'cpu_info')
    # ### end Alembic commands ###
