"""create device inventories table

Revision ID: b40c92558a20
Revises: b7f817caa742
Create Date: 2026-07-23 11:32:50.810965
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40c92558a20'
down_revision = 'b7f817caa742'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_inventories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('total_memory_mb', sa.Integer(), nullable=True),
    sa.Column('total_disk_mb', sa.Integer(), nullable=True),
    sa.Column('local_ip', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_inventories_device_id'), 'device_inventories', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_inventories_device_id'), table_name='device_inventories')
    op.drop_table('device_inventories')
    # ### end Alembic commands ###
