"""create devices table

Revision ID: b7f817caa742
Revises: 12b09a0f3f62
Create Date: 2026-07-21 15:04:25.055865
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f817caa742'
down_revision = '12b09a0f3f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'ONLINE', 'OFFLINE', 'ISOLATED', 'QUARANTINED', 'UNINSTALLED', name='devicestatus', native_enum=False), server_default='REGISTERED', nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_agent_id'), 'devices', ['agent_id'], unique=True)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_agent_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
